name: Reusable Attest

on:
  workflow_call:
    inputs:
      artifact:
        description: "Artifact to attest"
        required: false
        default: artifact
        type: string

jobs:
  attest:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      attestations: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact }}
      - uses: actions/attest-build-provenance@v1
        with:
          subject-path: "*"
