name: OIDC Token Dumper

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      greeting:
        description: "Greeting to echo"
        required: false
        type: string

jobs:
  # detect-env detects the reusable workflow's repository and ref for use later
  # in the workflow.
  oidc-dump:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed to detect the current reusable repository and ref.
    steps:
      - uses: hmarr/debug-action@v2
      - name: Environment
        env:
          GITHUB_CONTEXT: "${{ toJSON(github) }}"
        run: env
      - name: Request OIDC Token
        run: |
          # Request token
          curl "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=donottrust" \
            -H "Authorization: bearer ${ACTIONS_ID_TOKEN_REQUEST_TOKEN}" \
            -H "Accept: application/json; api-version=2.0" \
            -H "Content-Type: application/json" \
            --silent | jq -r '.value' > oidc_token
          echo -e "\nOIDC Token (decoded)"
          cat oidc_token | jq -R 'split(".") | .[0],.[1] | @base64d | fromjson'
